export const TYPES = {
  READ_STATE: "READ_STATE",
  SHOW_PRODUCT: "SHOW_PRODUCT",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ALL_ITEM: "REMOVE_ALL_ITEM",
  CLEAR_CART: "CLEAR_CART",
};
